markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num
gems: [jekyll-paginate]

blog:
    name: [cowboy]                                                # 博客名称
    description:  [Freedom]                                       # 博客描述
    title:                                               # 网页标题
    url:                                                 # 博客地址
    duoshuo: [2257241]                                            # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name: [陆宁]                                               # 作者名称
    email: https://luningcowboy@gmail.com                                              # 邮箱地址
    weibo:                                               # 微博地址
    github: https://github.com/luningcowboy                                              # GitHub地址
    logo:  [res\img\logo.jpg]                                              # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key